version: '3'
services:
  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://db/mega_pdv -user=mega_pdv -password=mega_pdv migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:9.6.7
    environment:
      - POSTGRES_USER=mega_pdv
      - POSTGRES_PASSWORD=mega_pdv
      - POSTGRES_DB=mega_pdv
    ports:
      - 5432:5432